# Generated by Django 4.1.3 on 2022-11-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0002_alter_details_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='vehicle_type',
            field=models.CharField(choices=[('Two Wheelers', 'Two Wheelers'), ('Three Wheelers', 'Three Wheelers'), ('Four Wheelers', 'Four Wheelers')], default='Two Wheelers', max_length=50),
        ),
    ]
