# Generated by Django 4.1.3 on 2022-11-04 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0003_alter_details_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='vehicle_number',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
