# Generated by Django 4.1.3 on 2022-11-04 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0004_alter_details_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='vehicle_model',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[a-zA-Z]*$', 'Only Text characters are allowed.')]),
        ),
    ]
